#!/bin/sh
if [ -d "../.cabal-sandbox" ]; then
  ghc -i../src \
    -no-user-package-db \
    -package-db ../.cabal-sandbox/*-packages.conf.d \
    -DSAMPLES "$@" -e main
elif [ -e "../stack.yaml" ]; then
  stack --stack-yaml "../stack.yaml" exec \
    ghc -- -i../src \
    -DSAMPLES "$@" -e main
else
  ghc -DSAMPLES "$@" -e main
fi
